function R = doub_trap(a, b, c, d, f)
  R = f(a,c) + f(a, d) + f(b,c) + f(b,d) + ...
   2*f((a+b)/2, c) + 2*f((a+b)/2, d) + 2*f(a, (c+d)/2) + ...
   2*f(b,(c+d)/2)+4*f((a+b)/2, (c+d)/2);
  R = R*(b-a)*(d-c)/16;
endfunction